### ISSUE TITLE
Incorrect tokenization of don't"

### ISSUE THREAD

**Issue by giorgio79** [winkjs/wink-tokenizer#22]
Demo
https://runkit.com/giorgio79/5c1a0288dd42f50012997019

![image](https://user-images.githubusercontent.com/283347/50208482-91929000-0371-11e9-97fd-050654d08e3b.png)

Should be
do n't

and

can 't

**Comment by sanjayaksaxena** [comment]
Hi @giorgio79 

Currently `wink-tokenizer` handles contractions involving `'` and not the other apostrophe mark — `’`. In the quoted example if **don’t** was written as **don't** (notice the difference between two apostrophe marks) then it would have worked correctly!

`can't` has been correctly tokenized as `ca` and `n't`; this is needed for subsequent correct part-of-speech tagging.

Some of these enhancements/fixes, including the [quoted phrase default configuration change](https://github.com/winkjs/wink-tokenizer/issues/20#issuecomment-448138695), are planned in next release.

As work around, we suggest replacing `’` by `'` in your text.

Best,
Sanjaya
