### ISSUE TITLE
Allow non-http url match

### ISSUE THREAD

**Issue by ksharlandjiev** [winkjs/wink-tokenizer#23]
May I suggest a small amendment in the rgxURL regex to:  
var rgxURL = /(?:https?:\/\/)?(?:[\da-z\.-]+)\.(?:[a-z\.]{2,6})(?:[\/\w\.\-\?#=]*)*\/?/gi;

the following will improve matching of url's without http(s)://

**Comment by sanjayaksaxena** [comment]
Hi @ksharlandjiev 

Thanks for your valuable suggestion.

We are working on our next release, where we plan to include such enhancements.

In the meantime, you may like to use [addRegex()](http://winkjs.org/wink-tokenizer/Tokenizer.html#addRegex) API to update the regex mapped to **`url`**.

Best,
Sanjaya
