### ISSUE TITLE
Add `startsAt` and `endsAt` to the result

### ISSUE THREAD

**Issue by maxmert** [winkjs/wink-tokenizer#25]
Hi!

First of all thanks for your awesome work. I wanted to ask if it make sense to add `startsAt` and `endsAt` fields to the result, which will represent the position of the token in original text, f.e.:

```js
myTokenizer.tokenize( 'hello, how are you?' );
// -> [ { value: 'hello', tag: 'greeting', startsAt: 0, endsAt: 4 },
// ...
 // ]
```

### Reason
If I'm using NER, then after recognition I want to mark the original text. It's possible, but with a lot of additional manipulations and possible errors, and I think it's significantly easier to get this information during tokenisation. What do you think?

Thanks in advance.

Best regards,
Maxim

**Comment by sanjayaksaxena** [comment]
Hi @maxmert 

Many thanks for your idea. 

We are working on a [next generation NLP](https://github.com/winkjs/wink-nlp) and will be shortly commencing its incremental release. This will include a high performance tokenizer, more accurate pos-tagger, NER and integration with word vectors. 

It will also have the requested feature along with capabilities to generate some kind of semantic HTML wherein POS, NER, etc. can be automatically highlighted by defining your own CSS.

In the meantime you may like to checkout [wink-ner](https://github.com/winkjs/wink-ner) – a language agnostic gazetteer-based Named Entity Recognizer (NER), which can be easily trained to suite specific needs.

Will keep you updated.

Best,
Sanjaya

**Comment by maxmert** [comment]
Thank you for your answer. I'll close the issue.
