### ISSUE TITLE
question on sanskrit

### ISSUE THREAD

**Issue by francescoagati** [winkjs/wink-tokenizer#28]
hi,
sanscrikt work only in devangari?
i have tried to use sanskrit with IAST but i dont understand if is tokenizer in the right mode.

this is an example

https://repl.it/@francescoagati/RigidUnusualDiscussions

**Comment by sanjayaksaxena** [comment]
Hi @francescoagati 

You are right — it works for Sanskrit written in Devanagri and currently does not support IAST. Here is how it will work with the verse that you tried in your example:
```javascript
// Load tokenizer.
var tokenizer = require( 'wink-tokenizer' );
// Create it's instance.
var myTokenizer = tokenizer();
// Tokenize a tweet.
var s = 'ईशा वास्यम् इदं सर्वं यत् किञ्च जगत्यां जगत् । तेन त्यक्तेन भुञ्जीथा मा गृधः कस्य स्विद्धनम्';
console.log( myTokenizer.tokenize( s ) );
```
Output:
```javascript
[ { value: 'ईशा', tag: 'word' },
  { value: 'वास्यम्', tag: 'word' },
  { value: 'इदं', tag: 'word' },
  { value: 'सर्वं', tag: 'word' },
  { value: 'यत्', tag: 'word' },
  { value: 'किञ्च', tag: 'word' },
  { value: 'जगत्यां', tag: 'word' },
  { value: 'जगत्', tag: 'word' },
  { value: '।', tag: 'punctuation' },
  { value: 'तेन', tag: 'word' },
  { value: 'त्यक्तेन', tag: 'word' },
  { value: 'भुञ्जीथा', tag: 'word' },
  { value: 'मा', tag: 'word' },
  { value: 'गृधः', tag: 'word' },
  { value: 'कस्य', tag: 'word' },
  { value: 'स्विद्धनम्', tag: 'word' } ]
```

We have noted the need for IAST and will try to include its support in our future releases.

Best,
Sanjaya

**Comment by sanjayaksaxena** [comment]
Hi @francescoagati 

I missed sharing that you could use [`addRegex()`](https://winkjs.org/wink-tokenizer/Tokenizer.html#addRegex) API to update the `word` regex to include the character set required by IAST to solve your problem.

Best,
Sanjaya

**Comment by francescoagati** [comment]
Really thanks i Will try with regex

**Comment by sanjayaksaxena** [comment]
Hi @francescoagati,

Thanks for closing the issue. We have tried with the following regex using `addRegex()` API and it seems to be working:

```javascript
var tokenizer = require( 'wink-tokenizer' );
// Create it's instance.
var myTokenizer = tokenizer();
// Update word regex.
myTokenizer.addRegex(/[a-z\u00C0-\u00D6\u00D8-\u00F6\u00F8-\u00FFāĀīĪūŪṛṚṝṜḷḶḹḸṃṂḥḤṭṬḍḌṅṄñÑṇṆśŚṣṢ][a-z\u00C0-\u00D6\u00D8-\u00F6\u00F8-\u00FFāĀīĪūŪṛṚṝṜḷḶḹḸṃṂḥḤṭṬḍḌṅṄñÑṇṆśŚṣṢ']*/gi, 'word');
// Tokenize the verse.
var s = 'īśā vāsyam idaṃ sarvaṃ yat kiñca jagatyāṃ jagat tena tyaktena bhuñjīthā mā gṛdhaḥ kasya sviddhanam';
console.log( myTokenizer.tokenize( s ) );
```

Output (from Runkit):
<img width="419" alt="image" src="https://user-images.githubusercontent.com/29990/56647769-a1174200-669f-11e9-86ee-1aaa7e1e8ad1.png">

Hope it helps.

Best,
Sanjaya

**Comment by francescoagati** [comment]
hi @sanjayaksaxena really thanks. i will try with this regex code
