### ISSUE TITLE
Incorrect handling of composite emojis

### ISSUE THREAD

**Issue by jdmunro** [winkjs/wink-tokenizer#30]
Certain emojis are made my essentially combining 2 others, for instance 🕵🏿 is a combination of the detective emoji and another skin tone: https://emojipedia.org/detective-dark-skin-tone/

The tokenizer is currently splitting these into 2 separate emojis in the output:

<img width="827" alt="Screenshot 2020-06-22 at 17 46 29" src="https://user-images.githubusercontent.com/17656/85314064-d3dde580-b4b0-11ea-9061-b1b2bebe8d39.png">

I think the expectation would be to return an array with a single token, the original emoji.

Code to reproduce:

```js
var tokenizer = require( 'wink-tokenizer' );
var myTokenizer = tokenizer();
var s = '🕵🏿';
console.log( myTokenizer.tokenize( s ) );
```

A potential solution would be to use this for the emoji regex: https://github.com/mathiasbynens/emoji-regex

**Comment by sanjayaksaxena** [comment]
Hello @jdmunro 

Thank you for highlighting the issue along  with a potential solution. Yes currently the emoji coverage is not high.

We will be initiating the work to address this shortly and will keep you posted.

Best,
Sanjaya

**Comment by jdmunro** [comment]
Thank you @sanjayaksaxena - let me know if I can help.

**Comment by sanjayaksaxena** [comment]
@jdmunro 

You are welcome to contribute.

The [emoji regex](https://github.com/winkjs/wink-tokenizer/blob/master/src/wink-tokenizer.js#L53) needs to be enhanced. Contribution guidelines are [here](https://github.com/winkjs/wink-tokenizer/blob/master/CONTRIBUTING.md).

Feel free to reach us out.

Best,
Sanjaya

**Comment by jdmunro** [comment]
@sanjayaksaxena I've implemented a fix in #31 using this: https://github.com/mathiasbynens/emoji-regex/blob/master/index.js#L5

**Comment by sanjayaksaxena** [comment]
Hello @jdmunro 

Many thanks for your contribution. We have processed the PR and also published the new version on NPM.

Would like to share that we are in the process of releasing a new integrated [wink-nlp](https://github.com/winkjs/wink-nlp). It is going to replace and retire most of our existing nlp related packages. We will continue to provide support on the existing ones for a reasonable length of time. Please see winkjs/wink-nlp#4. 

Request you to explore the same. Its documentation is unfolding at https://winkjs.org/wink-nlp/

You are welcome to contribute in this journey!

Once again thank you for your PR.

Best,
Sanjaya

**Comment by jdmunro** [comment]
Thanks @sanjayaksaxena! Will the new sentiment analysis work in a fundamentally different way to `wink-sentiment`?

**Comment by sanjayaksaxena** [comment]
Hello @jdmunro

It will not be fundamentally different! Current version of the [language model](https://github.com/winkjs/wink-eng-lite-model/releases/tag/0.1.0) may not be as good as `wink-sentiment` as it is WIP... eventually it is going to be better only. 

While new `wink-nlp's`  API is developer-focused and easier to use but it is not same as in `wink-sentiment`.

Best,
Sanjaya
