### ISSUE TITLE
RangeError: Maximum call stack size exceeded in wink-tokenizer.js

### ISSUE THREAD

**Issue by deemeetree** [winkjs/wink-tokenizer#32]
This error pops up pretty often when I perform intensive operations on `tokenizer` function (multiple strings processed at the same time). 

It is not treated in the module, so my whole Node.Js app stops. Is there a way to fix that?

The error that pops up is:

```
node_modules/wink-tokenizer/src/wink-tokenizer.js:215
            tokens = manageContraction( aword, tokens );
                     ^

RangeError: Maximum call stack size exceeded
```

**Comment by sanjayaksaxena** [comment]
@deemeetree can you help us in recreating the error?

We tried to run tokenizer in a loop for 1M unique text strings but could not hit this error.

It was run on 2.2 GHz Intel Core i7 processor with 16GB RAM on Node.js version 14.8.0. Each text string was about 100 character long and contained around 28 tokens. These tokens included contractions, emoji, emoticon, punctuation & words, etc.
