### ISSUE TITLE
Unexpected output in custom regex

### ISSUE THREAD

**Issue by transplatin** [winkjs/wink-tokenizer#35]
While adding a custom regex pattern to tokenizer, it is tokenizing unexpectedly or say re-tokenizing the already tokenized pattern and pushing into tokens. Also please add documentation support for adding custom patterns in wink-tokenizer. Have a nice day :)

**Input** 

```
var Tokens = require( 'wink-tokenizer' )();
const input = `Michael Joseph Jackson (August 29, 1958 – June 25, 2009)`;
Tokens.addRegex(/\((.*)\)/,"bracket","k")                    //
const data = Tokens.tokenize(input)
console.log(data)

```

**Output**

```
[
  { value: 'Michael', tag: 'word' },
  { value: 'Joseph', tag: 'word' },
  { value: 'Jackson', tag: 'word' },
  { value: '(August 29, 1958 – June 25, 2009)', tag: 'bracket' }, //The tokenizing should have stopped here
  { value: 'August', tag: 'word' },
  { value: '29', tag: 'number' },
  { value: ',', tag: 'punctuation' },
  { value: '1958', tag: 'number' },
  { value: '–', tag: 'alien' },
  { value: 'June', tag: 'word' },
  { value: '25', tag: 'number' },
  { value: ',', tag: 'punctuation' },
  { value: '2009', tag: 'number' },
  { value: 'August 29, 1958 – June 25, 2009', tag: 'bracket' }
]
```

**Comment by sanjayaksaxena** [comment]
Hi @transplatin 

We need to use the following regex to get the desired behavior:

`/\(.*?\)/g`

Giving below the screen capture of the running code at [RunKit](https://runkit.com/sanjaya/5fc1f4ab05757c001a0cb43d):
<img width="1027" alt="image" src="https://user-images.githubusercontent.com/29990/100495842-5c099a80-3175-11eb-882c-3edee0d69268.png">

The documentation is here https://winkjs.org/wink-tokenizer/Tokenizer.html#addRegex

**Comment by transplatin** [comment]
Thanks for your help. Now it works as expected :)
