### ISSUE TITLE
Function slows down when I use more than 2 custom regex expressions for tagging

### ISSUE THREAD

**Issue by deemeetree** [winkjs/wink-tokenizer#41]
I added 3 custom regex expressions for the tokenizer to identify `hashtag` with an underscore, `[squarebrackets]` and `[[wikilinks]]`. 

I noticed that when I use 3 regex expressions at once, it slows down the performance dramatically. For example, for a statement that is about 1 Mb long it takes about 15 seconds to process it. As soon as I remove 1 regex statement (any of them), it becomes really fast again. 

Here is my code below. Please, let me know what the problem may be, I would really appreciate it. 

If you don't have time, simply direct me to the part of the code where you think the problem may be, we can fork it, fix it, and make a pull request, so you can integrate the fix into the library.

```js
const myTokenizer = tokenizer();

myTokenizer.addRegex(/#[^\s!@#$%^&*()=+.\/,\[{\]};:'"?><]+/g, 'hashtag');
myTokenizer.addRegex(
      /(?<!\[)\[[^[\]]+](?!])/g,
      'squarebracket',
      'squarebracket',
    );
myTokenizer.addRegex(/[^[\]]+(?=]])/g, 'doublebracket', 'doublebracket');

const tokens = myTokenizer.tokenize(statement);

```

Thank you!

**Comment by sanjayaksaxena** [comment]
Immediate solution that I can think of is update hashtag regex in the `wink-tokenizer's` code — that way you will be able to remove a regex, which will ensure that the speed will improve as observed by you.

**Comment by sanjayaksaxena** [comment]
Have improved the hash tag detection and released a new version. Hope it will help you.

btw, the hashtag regex proposed above has a bug — it will detect # followed by an emoji also as a hashtag:

<img width="749" alt="image" src="https://user-images.githubusercontent.com/29990/151406706-baa188fe-646d-4545-bb6f-43e0c0d8c8a8.png">
